In [26]:
from tensorflow.keras.preprocessing.text import one_hot

In [27]:
## Sentences
sent=[ "the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "I am a good developer",
      "understand the meaning of words",
      "your videos are good",]

In [28]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [29]:
## Define the vocabulary size
voc_size=10000

In [30]:
## One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9690, 1637, 6543, 4263],
 [9690, 1637, 6543, 258],
 [9690, 1478, 6543, 3637],
 [6709, 3359, 6951, 6182, 7174],
 [6709, 3359, 6951, 6182, 6202],
 [2864, 9690, 6655, 6543, 2023],
 [2432, 6977, 7876, 6182]]

In [31]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

In [33]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9690 1637 6543 4263]
 [   0    0    0    0 9690 1637 6543  258]
 [   0    0    0    0 9690 1478 6543 3637]
 [   0    0    0 6709 3359 6951 6182 7174]
 [   0    0    0 6709 3359 6951 6182 6202]
 [   0    0    0 2864 9690 6655 6543 2023]
 [   0    0    0    0 2432 6977 7876 6182]]


In [34]:
## Feature representation
dim = 10

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential([
    Input(shape=(sent_length,), dtype='int32'),
    Embedding(input_dim=voc_size, output_dim=dim, name="embedding_1")
])

model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[[-1.50345452e-02, -7.13698938e-03,  1.34105571e-02,
         -1.66055672e-02, -1.64518952e-02,  4.83142175e-02,
         -2.73709297e-02, -2.02022195e-02,  7.60253519e-03,
         -3.11572198e-02],
        [-1.50345452e-02, -7.13698938e-03,  1.34105571e-02,
         -1.66055672e-02, -1.64518952e-02,  4.83142175e-02,
         -2.73709297e-02, -2.02022195e-02,  7.60253519e-03,
         -3.11572198e-02],
        [-1.50345452e-02, -7.13698938e-03,  1.34105571e-02,
         -1.66055672e-02, -1.64518952e-02,  4.83142175e-02,
         -2.73709297e-02, -2.02022195e-02,  7.60253519e-03,
         -3.11572198e-02],
        [-1.50345452e-02, -7.13698938e-03,  1.34105571e-02,
         -1.66055672e-02, -1.64518952e-02,  4.83142175e-02,
         -2.73709297e-02, -2.02022195e-02,  7.60253519e-03,
         -3.11572198e-02],
        [-3.74519341e-02, -1.77123398e-03, -3.03840768e-02,
          3.10162790e-02, -1.27576366e-02,  1.92126371e-02,
         -4.44944948e-03, -6.97256252e-03, -9.145628

In [42]:
embedded_docs[0]

array([   0,    0,    0,    0, 9690, 1637, 6543, 4263], dtype=int32)

In [47]:
model.predict(embedded_docs[0:1])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[-1.5034545e-02, -7.1369894e-03,  1.3410557e-02, -1.6605567e-02,
         -1.6451895e-02,  4.8314217e-02, -2.7370930e-02, -2.0202219e-02,
          7.6025352e-03, -3.1157220e-02],
        [-1.5034545e-02, -7.1369894e-03,  1.3410557e-02, -1.6605567e-02,
         -1.6451895e-02,  4.8314217e-02, -2.7370930e-02, -2.0202219e-02,
          7.6025352e-03, -3.1157220e-02],
        [-1.5034545e-02, -7.1369894e-03,  1.3410557e-02, -1.6605567e-02,
         -1.6451895e-02,  4.8314217e-02, -2.7370930e-02, -2.0202219e-02,
          7.6025352e-03, -3.1157220e-02],
        [-1.5034545e-02, -7.1369894e-03,  1.3410557e-02, -1.6605567e-02,
         -1.6451895e-02,  4.8314217e-02, -2.7370930e-02, -2.0202219e-02,
          7.6025352e-03, -3.1157220e-02],
        [-3.7451934e-02, -1.7712340e-03, -3.0384077e-02,  3.1016279e-02,
         -1.2757637e-02,  1.9212637e-02, -4.4494495e-03, -6.9725625e-03,
         -9.1456287e-03,  7.6480024e-03],
        [ 5.8591850e-03,  7.8976378e-03, -1.7759491e-02,  5.